### ISSUE TITLE
Benefit der App über Strava

### ISSUE THREAD

**Issue by PaulCharon** [SebieF/virtuelle_volkslaeufe_hackathon#4]
Moin, ich bin gerade über das App-docs auf euch gestoßen, finde euch aber nicht auf slack. Welchen benefit erhofft ihr euch von der App im vergleich zu Strava? Dort gibt es unter anderem auch folgenden Club: https://www.strava.com/clubs/anti-corona-running-league-594089

**Comment by markuswebert** [comment]
Wir möchten, dass du unsere App aufmachst und dann mit Leuten läufst, die auch gerade in dem Moment die gleiche Strecke laufen möchten. Man bekommt Live updates über den Lauffortschritt des Gegners, um so einen virtuellen Wettkampf zu erzeugen.
